#114 piano di qualifica: test
SWEet16-SWE-Group/docs pull request #168
Opened 2024-02-29 10:46 UTC by albyx97

Finita la parte dei test

2024-02-29 12:49 UTC, bzn0u95quudr7jutfjap requested changes

2024-02-29 12:52 UTC, AMike01 requested changes

2024-02-29 12:52 UTC, AMike01 commented on rtb/piano-di-qualifica/src/test.tex
> +\documentclass[a4paper, 11pt]{article}
Va tolta tutta la parte contenente da riga 1 a riga 28 perché già presente nel main.tex

2024-02-29 12:52 UTC, AMike01 commented on rtb/piano-di-qualifica/src/test.tex
> +Il gruppo SWEet16, durante lo sviluppo dell' RTB, ha eseguito esclusivamente un'unica tipologia di test sui vari componenti utilizzati nella programmazione del PoC. Per perseguire la correttezza del
Per segnare glossario mettere `$^{G}$ `

2024-02-29 12:52 UTC, AMike01 commented on rtb/piano-di-qualifica/src/test.tex
> +I \textit{test di accettazione} sono un tipo di test che viene utilizzato per verificare che il software soddisfi irequisiti prestabiliti dal capitolato e che sia pronto per essere consegnato al comm
typo "irequisiti"

2024-02-29 12:54 UTC, IuliusSignorelli commented
In generale, forse ci sta categorizzare i test fatti durante lo sviluppo del poc ,indicando la loro tipologia

2024-03-06 13:42 UTC, AMike01 approved these changes

2024-03-22 22:15 UTC, bzn0u95quudr7jutfjap approved these changes

2024-03-22 22:15 UTC, merged