close #98; piano di progettosrcmodello di sviluppotex
SWEet16-SWE-Group/docs pull request #170
Opened 2024-02-29 13:24 UTC by CHXSER

Dubbi su incrementi individuati

2024-03-06 13:41 UTC, AMike01 requested changes

2024-03-06 13:41 UTC, AMike01 commented on rtb/piano-di-progetto/src/modello-di-sviluppo.tex
> +multipli che corrispondono ciascuno a un aumento delle funzionalità. Questo approccio richiede una
```suggestion
multipli che corrispondono ciascuno ad un aumento delle funzionalità. Questo approccio richiede una
```

2024-03-06 13:41 UTC, AMike01 commented on rtb/piano-di-progetto/src/modello-di-sviluppo.tex
> +    02 & Implementazione funzionalità prenotazione & UC 2.? \\
Guardare numero Use Case su documento Analisi dei Requisiti

2024-03-06 13:41 UTC, AMike01 commented on rtb/piano-di-progetto/src/modello-di-sviluppo.tex
> +    03 & Implementazione ordinazione & UC 2.?\\
Stessa cosa per ordinazione e login

2024-03-22 15:52 UTC, bzn0u95quudr7jutfjap approved these changes

2024-03-23 10:36 UTC, AMike01 approved these changes

2024-03-23 11:34 UTC, merged