105 norme di progettosrcverificatex
SWEet16-SWE-Group/docs pull request #215
Opened 2024-03-21 12:06 UTC by CHXSER

2024-03-21 13:46 UTC, AMike01 requested changes

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +\end{itemize}
Scopo aspettative e descrizione vanno unite all'interno di un unica subsubsection, per rendere la struttura del documento omogenea.

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +    \item \textbf{Analisi dinamica: } richiede l'esecuzione dell'oggetto di verifica.
```suggestion
    \item \textbf{Analisi statica:} Non richiede l'esecuzione dell'oggetto di verifica;
    \item \textbf{Analisi dinamica:} Richiede l'esecuzione dell'oggetto di verifica.
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +        \item Correzione degli errori
```suggestion
        \item Pianificazione;
        \item Lettura;
        \item Discussione;
        \item Correzione degli errori.
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +        \item Correzione degli errori
```suggestion
        \item Pianificazione;
        \item Definizione di una lista di controllo;
        \item Lettura;
        \item Correzione degli errori.
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +e il rispetto dei requisiti specificati
```suggestion
e il rispetto dei requisiti specificati.
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +e le specifiche indicate. Poiché non richiede l'esecuzione dell'oggetto in esame, questo tipo di analisi
```suggestion
e le specifiche indicate. \\
Poiché non richiede l'esecuzione dell'oggetto in esame, questo tipo di analisi 
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +    \item Essere ripetibile: Dato un determinato input, si deve ottenere sempre
```suggestion
    \item \textbf{Essere ripetibile:} Dato un determinato input, si deve ottenere sempre
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +L'automatizzazione sarà realizzata mediante strumenti dedicasti non ancora definiti dal gruppo.
```suggestion
L'automatizzazione sarà realizzata mediante strumenti dedicati non ancora definiti dal gruppo.
```

2024-03-21 13:46 UTC, AMike01 commented on rtb/norme-di-progetto/src/verifica.tex
> +    \item Accertamento dell'adeguato rispetto delle norme tipografiche e di formattazione stabilite;
```suggestion
    \item Accertamento dell'adeguato rispetto delle norme tipografiche e di formattazione stabilite, descritte nella sezione 3.1.6 di questo documento;
```

2024-03-23 14:02 UTC, bzn0u95quudr7jutfjap approved these changes

2024-03-24 10:03 UTC, AMike01 approved these changes

2024-03-24 15:18 UTC, merged