close #112; Gestione configurazione
SWEet16-SWE-Group/docs pull request #216
Opened 2024-03-22 15:31 UTC by CHXSER

2024-03-23 10:35 UTC, AMike01 requested changes

2024-03-23 10:35 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    \emph{Git}. Il gruppo fa pieno uso delle funzionalità di \emph{GitHub} tra cui:
```suggestion
    Per il progetto viene usato \emph{GitHub}$^{G}$, che a sua volta implementa il sistema di versionamento 
    \emph{Git}$^{G}$. Il gruppo fa pieno uso delle funzionalità di \emph{GitHub} tra cui:
```

Giusto per avere qualche termine in glossario

2024-03-23 10:35 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    Si è deciso di utilizzare un'unica repository contenente il codice sorgente per documentazione e \emph{PoC}.
```suggestion
    Si è deciso di utilizzare un'unica repository contenente il codice sorgente per la documentazione e per il \emph{PoC}$^{G}$.
```

2024-03-23 10:35 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    All'interno della repository troviamo una cartella per ogni documento denominata \emph{nome-documento}. Inoltre la
In realtà non è proprio così, infatti la repo è composta da 3 cartelle così divise: 

- Template: contenente il template per il documento latex;
- Candidatura: contenente i documenti relativi alla candidatura. Aggiungere inoltre quali documenti contiene questa cartella (i nomi dei documenti).
- RTB: contenente i documenti relativi alla revisione. Aggiungere inoltre da quali cartelle è formato (l'idea sarebbe di suddividere in documentazione interna e documentazione esterna, e fare una lista di tutti i documenti contenuti in ognuno di esse).

Ricordarsi di nominare anche i verbali.

2024-03-23 10:35 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +        \item \textbf{rtb-documentazione-main}: Il branch dedicato alla creazione/modifica dei documenti.
```suggestion
        \item \textbf{rtb-documentazione-main}: Il branch dedicato alla creazione/modifica dei documenti relativi alla revisione RTB.
```

2024-03-23 10:35 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    effettuare una \emph{pull request} con verifica obbligatoria per integrare le modifiche nel branch. Se la verifica non è
Aggiungere pull request al glossario
```suggestion
    effettuare una \emph{pull request}$^{G}$ con verifica obbligatoria per integrare le modifiche nel branch. Se la verifica non è
```

2024-03-23 13:49 UTC, bzn0u95quudr7jutfjap approved these changes

2024-03-24 10:02 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +        \item \textbf{Template:} contenente il template per il documento latex;
```suggestion
        \item \textbf{Template:} contenente il template per il documento \LaTeX;
```

2024-03-24 10:02 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    Ciascun documento segue la convenzione di nomenclatura \emph{Nome\_Documento} ad eccezione dei verbali che vengono
Mi pare che i nomi dei documenti fossero tutti in minuscolo, controlla nella sezione documentazione delle ndp

2024-03-25 09:51 UTC, AMike01 requested changes

2024-03-25 09:51 UTC, AMike01 commented on rtb/norme-di-progetto/src/gestione-configurazione.tex
> +    Ciascun documento segue la convenzione di nomenclatura \emph{Nome\_Documento}, ad eccezione dei verbali che vengono
Cito testualmente dalla sezione 3.1.6.1 di questo documento: 

> Il nome di ogni file inizia con la lettera maiuscola;
Se il nome comprende più parole queste iniziano per lettera minuscola e sono separate da ’_’;

```suggestion
    Ciascun documento segue la convenzione di nomenclatura \emph{Nome\_documento}, ad eccezione dei verbali che vengono 
```

2024-03-25 15:57 UTC, AMike01 approved these changes

2024-03-25 18:02 UTC, merged